#+BLOG:panghuli
#+POSTID:3256
#+DATE:Tue Aug 12 10:19:22 2014
#+OPTIONS:
#+CATEGORY:专业知识
#+TAGS:Emacs
#+DESCRIPTION:主要如何在 Emacs 中提供代码跳转、语法分析等功能。
#+TITLE:如何使用 Emacs 浏览源码

* 需求：该具备什么样的特性
理想的 IDE 至少应该支持以下功能：
+ 代码导航，包括源文件、变量、函数的查找和跳转
+ 代码补全

* 现状：常用插件介绍及对比
Emacs 中代码的查找和跳转都是通过 tag 进行的。tag 代表程序或文档中的一个子单元。程序源码中，tags 代表了程序的语法元素：函数、子程序、数据类型、宏等等。文档中，tags 代表了章、节、附录等等。每个 tag 都指明了对应的子单元所在文件的文件名，以及定义的位置。tag table 记录了通过扫描程序的源码文件或文档提取出来的 tags[fn:1]，tags 文件通常命名为 tags 或者 TAGS。

+ Emacs 产生 tags table 的默认工具是 etags，支持22种语言，包括 C、C++、Java、LaTex、Lisp、Scheme、Lua、PHP、Perl、Python等等。进一步了解请阅读 Emacs Manual 相关章节[fn:1]。除了 etags， 常用的 tags 插件还有 ebrowse[fn:2]、exuberant ctags[fn:3]、cscope[fn:4][fn:5]、GNU Global[fn:6]、Semantic[fn:7]。stackoverfllow上面有一篇文章[fn:8]主要讲述他们之间的关系。
+ Ebrowse 采取的机制与 etags 类似，但只能用于 C++，并对 C++ 进行了定制。
+ exuberant ctags 同样可以产生 TAGS 文件，而且支持更多的语言（41种），针对语言对象产生元数据信息要更加丰富，但可惜的是 Emacs 不能解析这些额外的数据。

+ cscope 是针对C、C++、java的集成化代码浏览工具，而且更加强力（至少对于 C/C++ 和 Java 来说如此），通过这个玩意不仅可以查到符号声明和定义，还可以查找所有引用。Emacs中可以通过 xcscope.el 来使用。
+ GNU Global是一个源码标记系统，和上面工具不同的是它独立于编辑器。Emacs 有很多的插件可以使用：xgtags.el、ggtags.el、helm-gtags.el等。
+ 为了智能补全，需要一个源码分析器，比如semantic，否则不知道对象（或者实例）的类型和它们可以调用的方法。semantic带来了代码的自动感知，尽管支持语言较少，但毕竟缩短了 Emacs 和 IDE之间差距。

* 解决方案：强强结合
综上所述：
+ tag文件最主要的用途来查找类、方法、函数、常量等的声明和定义。
+ ctags 和 etags使用的是文本文件存储tags，而 cscope 和 GNU global 使用的是 键值对的数据库，并且提供搜索和增量更新 tags 文件。
+ C/C++ 工程更加依赖cscope， 其他类型的工程更加依赖 ctags。

所以最终解决方案应该是：
+ 首先安装好 exuberant ctags。

#+NAME:查看ctags版本
#+BEGIN_SRC shell
E:\myfiles\linux-3.16>ctags --version
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Jul  9 2009, 17:05:35
  Addresses: <dhiebert@users.sourceforge.net>, http://ctags.sourceforge.net
  Optional compiled features: +win32, +regex, +internal-sort
#+END_SRC

+ 将 ctags 作为 GNU Global 的一个分析插件，编译 Global 时候启用支持。
#+NAME:查看ctags版本
#+BEGIN_SRC shell
$ ./configure --with-exuberant-ctags=/usr/local/bin/ctags
$ make && sudo make install
#+END_SRC

+ cscope也作为 GNU Global的一个客户端， Global 本身提供命令 gtags-cscope 来作为cscope的一个接口，这样，cscope 本身使用 Global 作为一个搜索引擎来替代自身包含的。 但还是觉得如果工程比较大的话，xcscope朝赵比较慢，而且ctags和Global的支持已经足够了。
#+NAME:
#+BEGIN_SRC shell
$ gtags-cscope          # this is GLOBAL version of cscope
#+END_SRC


* 参考链接
[fn:1] [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Tags.html#Tags][Emacs Manual -- Tags Tables]]
[fn:2] [[http://www.gnu.org/software/emacs/manual/html_mono/ebrowse.html#Top][Emacs Manual -- Ebrowse]]
[fn:3] [[http://ctags.sourceforge.net/][official Exuberant Ctags web site]]
[fn:4] [[http://cscope.sourceforge.net/][official cscope web site]]
[fn:5] [[http://www.emacswiki.org/emacs/CScopeAndEmacs][Emacs wiki -- cscope and Emacs]]
[fn:6] [[http://www.gnu.org/software/global/][official GNU Global web site]]
[fn:7] [[http://www.gnu.org/software/emacs/manual/html_mono/semantic.html][Semantic Manual]]
[fn:8] [[http://stackoverflow.com/questions/12922526/tags-for-emacs-relationship-between-etags-ebrowse-cscope-gnu-global-and-exhu][Tags for Emacs: Relationship between etags, ebrowse, cscope, GNU Global and exhuberant ctags]]
[fn:9] [[http://easwy.com/blog/archives/exuberant-ctags-chinese-manual/][Exuberant Ctags中文手册]]
