#+BLOG: panghuli_blog
#+POSTID: 60
#+DATE: [2014-11-09 周日 23:42]
#+CATEGORY:专业知识
#+TAGS:ubuntu
#+DESCRIPTION:Ubuntu使用笔记
#+TITLE:【Ubuntu】使用笔记
#+OPTIONS:toc:3
* 安装
** 硬盘安装
使用EFI引导模式安装，由于EFI能够自动识别磁盘根目录下的EFI文件夹中的引导文件，所以只需要把ISO文件解压到U盘即可，主要U盘需要先格式化为FAT32位的，这里有一个安装教程，安装过程中最重要的一点是要建立EFI引导分区，否则不能引导成功。

安装过程中如可以下载更新的话推荐直接下载更新，因为有次安装的之后更新系统导致一些软件不能正确安装。此问题待有时间深究一下。
** 虚拟机安装
使用 VMware Workstation 安装。有必要的话安装 vmware-tools。
* 选择最快的软件源,更新软件。
#+NAME: update
#+BEGIN_SRC bash :export code :tangle no
  # 安装必备的开发包
  sudo apt-get install -y build-essential automake autoconf libtool wget openssh-server
  sudo apt-get update
  sudo apt-get upgrade
  # 新建工程目录，放置之后的工程项目
  mkdir ~/projects/
#+END_SRC

* 安装输入法
#+HTML:<!--more-->
** sogou 输入法
#+NAME: install-sogou
#+BEGIN_SRC bash
  sudo add-apt-repository ppa:fcitx-team/nightly
  sudo apt-get update
#+END_SRC
安装之后sogou出现不能 shift 不能切换中英文等问题，所以不用了。
** ibus-rime中州韵
目前（2015.02.10）通过ppa安装后语言栏不能出现图标，所以建议使用手动安装，参看 [[https://code.google.com/p/rimeime/wiki/RimeWithIBus][ibus-rime安装说明]] 中 Manual Installation小节。考虑到Google被封锁，整理安装过程如下：
#+NAME: install-rime
#+BEGIN_SRC bash
  cd ~/projects
  wget -P ~/Downloads http://dl.bintray.com/lotem/rime/brise-0.35.tar.gz
  wget -P ~/Downloads http://dl.bintray.com/lotem/rime/librime-1.2.tar.gz
  wget -P ~/Downloads http://dl.bintray.com/lotem/rime/ibus-rime-1.2.tar.gz
  sudo apt-get install cmake libboost-all-dev libgoogle-glog-dev libgtest-dev libibus-1.0-dev libnotify-dev libkyotocabinet-dev kyotocabinet-utils libmarisa-dev libopencc-dev libyaml-cpp-dev
  tar xzf ~/Downloads/librime-*.tar.gz
  tar xzf ~/Downloads/brise-*.tar.gz
  tar xzf ~/Downloads/ibus-rime-*.tar.gz
  cd ibus-rime
  # do this as normal user
  ./install.sh
#+END_SRC
[[https://www.byvoid.com/blog/recommend-rime][byvoid关于rime的简单介绍]]
* 安装版本控制工具
** Git
*** 安装
#+NAME: install-git
#+BEGIN_SRC bash
  sudo apt-get -y install git
#+END_SRC
*** 配置 [[http://git-scm.com/book/zh/v1][《Pro Git 中文版》]]
#+NAME: configure-git
#+BEGIN_SRC bash
  git --version
  # 查看配置信息
  git config --list
  git config --global user.name "phenix3443"
  git config --global user.email "phenix3443@gmail.com"
#+END_SRC
*** 生成ssh-key，并添加到github

* 安装 goagent
[[https://github.com/goagent/goagent][goagent on github]]

Linux 下需要安装一些依赖组件：
+ gevent 1.0(提升多线程性能，强烈建议安装)
+ greenlet (gevent的依赖，一般安装gevent会自动安装)
+ python-vte(基于GTK的简单GUI所需)
+ python-openssl 0.13(生成证书所需，强烈建议安装，如删除了goagent自动证书则必须安装)
+ pycrypto(RC4加密所需，建议安装)
+ python-appindicator(Unity桌面下的托盘组件，其他桌面不必安装)

注意插件安装的先后顺序最好不要改,因为排列在后面的插件需要依赖前面的插件才能运行起来.并且自己酌情安装,比如你不是使用的ubuntu那么和Unity桌面相关的玩意儿,就可以不需要了,把它从上述命令里剔除掉就可以.

如果greenlet版本低于0.4.0会导致gevent装不上，但最新的ubuntu更新下来的greenlet就已经是0.4.2了,所以不用太担心.如果是老版本的那么就需要查询下更新greenlet了.

#+NAME: install-goagent-dependency
#+BEGIN_SRC bash :export code :tangle no
  # 安装第三方软件
  sudo apt-get install python-dev python-greenlet python-gevent python-vte python-openssl python-crypto python-appindicator
  cd ~/projects/
  git clone git@github.com:goagent/goagent.git
  cd goagent
  # 上传服务器代码
  python server/upload.py
  # 修改 appid
  gedit local/proxy.ini
#+END_SRC

使用 root 账户身份去启动goagent.会发现有新的证书被生成了.

Firefox可以直接在浏览器中导入证书，但是 chrome 证书机制不同，需要使用公用nssdb库，需要做以下配置。
#+NAME: chrome-ca
#+BEGIN_SRC bash :export code :tangle no
  # 安装证书
  sudo apt-get install libnss3-tools
  # 查看现有证书目录
  certutil -d sql:$HOME/.pki/nssdb -L
  # 如果出现以下错误：
  certutil: function failed: security library: bad database.
  # 说明证书损坏，需要重建：
  rm -fr ~/.pki/
  mkdir -p ~/.pki/nssdb
  chmod 700 ~/.pki/nssdb
  certutil -d sql:$HOME/.pki/nssdb -N # 之后输入密码
  # 导入 goagent 证书
  certutil -d sql:$HOME/.pki/nssdb -A -t "C,," -n GoAgent -i "~/projects/goagent/local/CA.crt"
  # 开机自动
  sudo python ~/projects/goagent/local/addto-startup.py
#+END_SRC
到这里,恭喜,已经全部完成了.可以尽情的使用goagent了.
注意：
chrome一切都配置好了，打开谷歌等网站就提示：Your connection is not private,可能是之前chrome导入的goagent证书有问题，可以尝试在 https/ssl里先删掉老的goagent证书，然后重新导入一下。
* 安装Shadowsocks
有些情况下goagent并不是很好用，这里推荐一款VPN软件: [[https://github.com/shadowsocks][shadowsocks]]
#+NAME: install-pidgin
#+BEGIN_SRC bash
  sudo add-apt-repository ppa:hzwhuang/ss-qt5
  sudo apt-get update
  sudo apt-get install shadowsocks-qt5
#+END_SRC
当然你还需要一个vpn服务器，推荐使用shadowsock+vps自己搭建一个vpn实施。
* 安装 chrome
** 标签页乱码
  打开/etc/fonts/conf.d/49-sansserif.conf这个文件：
	#+NAME: chrome-tab-error
	#+BEGIN_SRC bash
      sudo gedit /etc/fonts/conf.d/49-sansserif.conf
	#+END_SRC
  然后修改倒数第四行的字体为WenQuanYi Zen Hei，如下:
	#+NAME: chrome-problem-2
	#+BEGIN_SRC xml
      <?xml version="1.0"?>
      <!DOCTYPE fontconfig SYSTEM "fonts.dtd">
      <fontconfig>
        <!--
            If the font still has no generic name, add sans-serif
        -->
        <match target="pattern">
          <test qual="all" name="family" compare="not_eq">
            <string>sans-serif</string>
          </test>
          <test qual="all" name="family" compare="not_eq">
            <string>serif</string>
          </test>
          <test qual="all" name="family" compare="not_eq">
            <string>monospace</string>
          </test>
          <edit name="family" mode="append_last">
            <string>WenQuanYi Zen Hei</string>
          </edit>
        </match>
      </fontconfig>
	#+END_SRC
之后flash中文和chromium中文都可以正常显示了。
* 安装flash
+ chrome安装教程：[[https://wiki.ubuntu.com/Chromium/Getting-Flash"%20title%3D"Getting-Flash][Getting-Flash]]
+ Firefox 安装：
#+NAME: firefox-install-flash
#+BEGIN_SRC bash
  sudo add-apt-repository ppa:nilarimogard/webupd8
  sudo apt-get update
  sudo apt-get install freshplayerplugin
#+END_SRC

* 安装 emacs
#+NAME: install-emacs
#+BEGIN_SRC bash :export code :tangle no
  # 安装第三方软件
  sudo apt-get -y install libxaw7-dev xaw3dg-dev libxmp-dev libpng12-dev libjpeg-dev libgif-dev libtiff-dev libgpm-dev libgconf2-dev libxml2-dev libfreetype6-dev  libgnutls-dev libm17n-dev libotf-dev libxft-dev libselinux1-dev librsvg2-dev texinfo

  # 下载 emacs-24.4 release 版本
  wget -P ~/Downloads http://mirrors.ustc.edu.cn/gnu/emacs/emacs-24.4.tar.gz
  tar zxf ~/Downloads/emacs-24.4.tar.gz
  cd emacs-24.4

  # 或者 emacs 开发版本
  git clone -b master git://git.sv.gnu.org/emacs.git
  cd emacs
  ./autogen.sh
  # 安装
  ./configure && make && sudo make install && make clean
  # 配置
  git clone git@github.com:phenix3443/emacs.d.git ~/.emacs.d
#+END_SRC

* ubuntu 同步时间命令
经常在虚拟机中使用，重新恢复之后经常需要同步网络时间：
#+NAME: sync-time
#+BEGIN_SRC bash :export code :tangle no
  sudo ntpdate cn.pool.ntp.org
#+END_SRC
* 使用evernote
在windows上面经常使用evernote作学习记录，但是该软件没有linux版本，不过有人做了第三方的客户端everpad可以使用：[[http://www.omgubuntu.co.uk/2012/09/use-evernote-in-ubuntu-with-everpad][Install Evernote Client (Everpad) in Ubuntu 14.04]]
注意的是：登录的时候需要在任务栏图标上右击才会出现登录窗口
* 安装virtualbox
  [[https://www.virtualbox.org/wiki/Linux_Downloads][Download]]
  #+NAME: install-virtualbox
  #+BEGIN_SRC bash
    sudo sh -c 'echo "deb http://download.virtualbox.org/virtualbox/debian trusty contrib" >> /etc/apt/sources.list.d/virtualbox.list'
    wget -q http://download.virtualbox.org/virtualbox/debian/oracle_vbox.asc -O- | sudo apt-key add -
    sudo apt-get update
    sudo apt-get install virtualbox-4.3
  #+END_SRC
* 聊天工具 Pidgin
* 安装播放器 SMPlayer
* 安装 Uget 与 aria2 作为下载工具。
* 安装最好的截图软件 Shutter
* 安装7zip作为解压工具 p7z-ful
* 安装 texlive-full
#+NAME: install-aria2
#+BEGIN_SRC bash
  sudo add-apt-repository ppa:pidgin-developers/ppa #pidgin
  sudo add-apt-repository ppa:rvm/smplayer #smplayer
  sudo add-apt-repository ppa:plushuang-tw/uget-stable #uget
  sudo add-apt-repository ppa:t-tujikawa/ppa #aria2
  sudo apt-get update
  sudo apt-get install -y pidgin smplayer smplayer-themes uget aria2 shutter p7z-full texlive-full texmaker
#+END_SRC

* Google Hangout
#+NAME: install hangout
#+BEGIN_SRC bash
  wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  sudo sh -c 'echo "deb http://dl.google.com/linux/talkplugin/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
  sudo apt-get update
  sudo apt-get install google-talkplugin
#+END_SRC
* 安装有道词典
[[https://github.com/justzx2011/openyoudao][项目网址]]
